package com.experis.de.MeFit.models;

import com.fasterxml.jackson.annotation.JsonGetter;
//import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.media.Schema;
//import lombok.Data;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Entity
@Table(name = "Exercise")
@Schema(description = "Exercise Model")
public  @Getter
        @Setter
        @RequiredArgsConstructor
        class Exercise {

    //autogenerated ID which never has to be defined in future functions.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model
    @Column(name="name",
            nullable = false,
            unique=true,
            columnDefinition = "TEXT")
    private String name;

    @Column(name="description",
            nullable = false,
            columnDefinition = "TEXT")
    private String description;

    //related data
    //exercise - workouts - relation
    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH})
    @JoinTable(
            name="exercise_workouts",
            joinColumns = {@JoinColumn(name="exercise_id")},
            inverseJoinColumns = {@JoinColumn(name="workout_id")}
    )
    private Set<Workout> workouts = new HashSet<>();

    // restricts the output to a List of IDs of the muscleGroups
    @JsonGetter("workouts")
    public List<String> workoutsGetter() {
        if(workouts != null) {
            return workouts.stream()
                    .map(workout -> {
                        return "/api/v1/workouts/" + workout.getId();
                    }).collect(Collectors.toList());
        }
        return null;
    }


    //related data
    //workout - muscleGroup - relation
    @ManyToOne(cascade = {/*CascadeType.ALL, */CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH})
    @JoinColumn(name="muscleGroup_id")
    private MuscleGroup muscleGroup;

    //restricts the output to the muscle group ID
    @JsonGetter("muscleGroup")
    public String muscleGroup() {
        if(muscleGroup != null){
            return "/api/v1/muscleGroup/" + muscleGroup.getId();
        }else{
            return null;
        }
    }


    //related data
    //workout - exercise - relation
    //@ManyToOne(cascade = {/*CascadeType.ALL, */CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH})
    //@JoinColumn(name="workout_id")
    //private Workout workout;

    //restricts the output to the workout ID
/*
    @JsonGetter("workout")
    public String workout() {
        if(workout != null){
            return "/api/v1/workout/" + workout.getId();
        }else{
            return null;
        }
    }


    //related data
    //workout - exercise - relation
    //@ManyToOne(cascade = {/*CascadeType.ALL, *///CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH})
    //@JoinColumn(name="workout_id")
    //private Workout workout;

    //restricts the output to the workout ID
/*
    @JsonGetter("workout")
    public String workout() {
        if(workout != null){
            return "/api/v1/workout/" + workout.getId();
        }else{
            return null;
        }
    }
    */

}

