package com.experis.de.MeFit.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.v3.oas.annotations.media.Schema;
//import lombok.Data;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Entity
@Table(name = "MuscleGroup")
@Schema(description = "MuscleGroup Model")
public  @Getter
        @Setter
        @RequiredArgsConstructor
        class MuscleGroup {

    //autogenerated ID which never has to be defined in future functions.
    @ApiModelProperty(notes = "ID of the muscle group", name = "id", value = "1")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model
    @Column(name="name",
            nullable = false,
            columnDefinition = "TEXT")
    private String name;


    //related data
    //muscleGroup - exercises - relation
    @OneToMany(cascade = {/*CascadeType.ALL, */CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH}, mappedBy="muscleGroup")
    public Set<Exercise> exercises = new HashSet<>();

    // restricts the output to a List of IDs of the exercises
    @JsonGetter("exercises")
    public List<String> exercises() {
        if(exercises != null) {
            return exercises.stream()
                    .map(exercise -> {
                        return "/api/v1/exercises/" + exercise.getId();
                    }).collect(Collectors.toList());
        }
        return null;
    }

    /*
    //restricts the output to the exercise ID
    @JsonGetter("exercise")
    public String exercise() {
        if(exercises != null){
            return "/api/v1/exercise/" + exercises.getId();
        }else{
            return null;
        }
    }
     */
}
