package com.experis.de.MeFit.models;

import io.swagger.annotations.ApiModelProperty;
import io.swagger.v3.oas.annotations.media.Schema;
//import lombok.Data;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Entity
@Table(name = "Profile")
@Schema(description = "Profile Model")
public  @Getter
        @Setter
        @RequiredArgsConstructor
        class Profile {

    //autogenerated ID which never has to be defined in future functions.
    @ApiModelProperty(notes = "ID of the profile", name = "id", value = "1")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model

    @Column(name="weight",
            nullable = false,
            columnDefinition = "TEXT")
    private String weight;

    @Column(name="height",
            nullable = false,
            columnDefinition = "TEXT")
    private String height;

    @Column(name="fitnessLevel",
            nullable = false,
            columnDefinition = "TEXT")
    private String fitnessLevel;

    @OneToOne
    @JoinColumn(name = "user_id")
    private Person person;

    @OneToOne
    @JoinColumn(name = "goal_id")
    private Goal goal;
}
