package com.experis.de.MeFit.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.v3.oas.annotations.media.Schema;
//import lombok.Data;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Entity
@Table(name = "Program")
@Schema(description = "Program Model")
public  @Getter
        @Setter
        @RequiredArgsConstructor
        class Program {

    //autogenerated ID which never has to be defined in future functions.
    @ApiModelProperty(notes = "ID of the program", name = "id", value = "1")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model
    @Column(name="name",
            nullable = false,
            columnDefinition = "TEXT")
    private String name;

    @Column(name="category",
            nullable = false,
            columnDefinition = "TEXT")
    private String category;

    //workouts - programs - relation
    @ManyToMany(cascade = {/*CascadeType.ALL, */CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH}, mappedBy = "programs")
    public Set<Workout> workouts= new HashSet<>();

    //restricts the output to a List of character IDs
    @JsonGetter("workouts")
    public List<String> workouts() {
        return workouts.stream()
                .map(workout -> {
                    return "/api/v1/workouts/" + workout.getId();
                }).collect(Collectors.toList());
    }
}
